name: Execução dos testes e2e API
on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
jobs:
  mvn-run:
   runs-on: ubuntu-latest
   timeout-minutes: 10
   steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Maven
        uses: s4u/setup-maven-action@v3.9.9
        with:
          java-version: 23
          maven-version: 3.9.9

      - name: Run tests
        run: mvn clean install
